### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by XHHP0913** [Betahj/PairABSA#1]
您好，请问为什么您在论文《Seeking Common but Distinguishing Difference, A Joint Aspect-based Sentiment Analysis Model》说公开源代码，但是打开github却是空项目？

**Comment by Betahj** [comment]
您好，由于我最近事情繁多，还没有来得及上传代码，等我们整理好，会尽快上传的。我们的实现大部分是基于Wang and Lu (2020)的开源项目：（https://github.com/LorrinWWW/two-are-better-than-one）
如果急需参考，也可以在他们的基础上作适当修改。

**Comment by Betahj** [comment]
您好，由于我最近事情繁多，还没有来得及上传代码，等我们整理好，会尽快上传的。我们的实现大部分是基于Wang and Lu (2020)的开源项目：（https://github.com/LorrinWWW/two-are-better-than-one）
如果急需参考，也可以在他们的基础上作适当修改。
